config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#home", as: "home_path"
  
  get 'climbers/new'
  get 'climber/profile', to: 'climbers#profile'
  # get 'climbers/login', to: 'climbers#login'
  post 'climbers/login', to: 'climbers#process_login'
  get 'climbers/logout', to: 'climbers#logout'
  get 'climbers/welcome', to: 'climbers#welcome'
  #trim this file down to just the routes you need upon refactoring
  resources :communities
  resources :locations
  resources :projects
  resources :routes
  resources :climbers
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'post/delete', to: 'posts#destroy'

  get 'climber/remove_community', to: 'climbers#remove_community'
  get 'climber/remove_route', to: 'climbers#remove_route'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/climber.rb
class Climber < ApplicationRecord
  has_secure_password

  has_many :projects
  has_many :routes, through: :projects
  has_many :posts
  has_many :communities, through: :posts
  has_many :comments
  
  validates :username, uniqueness: {case_sensitive: false, message: " must be unique."}
  

  def delete_route(route_obj)
    @climber.routes.each do |route|
      if route == route_obj
        route.delete
      end
    end
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :climber
  belongs_to :post

  validates :message, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :posts
  has_many :climbers, through: :posts
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :routes



  def all_routes
    self.routes.map
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :climber
  belongs_to :community
  has_many :comments

  # validates :subject, presence: true
  # validates :content, presence: true
  
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :climber
  belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :location
  has_many :projects
  has_many :climbers, through: :projects

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :difficulty, :location, presence: true
  validates :style, presence: true

  def add_like
    self.likes += 1
    self.save
  end

end

app/models/user.rb
class User < ApplicationRecord


  

  


end

app/controllers/climbers_controller.rb
class ClimbersController < ApplicationController
  before_action :find_climber, only: [:show, :edit, :delete, :update]
  before_action :authorized, except: [:process_login, :new, :create]

  def index
    @climbers = Climber.all
  end

  def show
    id = params[:id]
    @climber = Climber.find(id)
    @communities = @climber.communities.uniq
    @routes = @climber.routes.uniq
    cookies["this_page_climber"] = @climber.id
  end
  
  def welcome
    @api = get_users_weather()["current"]
    @routes = current_user.routes.uniq
  end

  def login
  end

  def process_login
    climber = Climber.find_by(username: params[:username])
    if climber && climber.authenticate(params[:password])
      session[:climber_id] = climber.id
      redirect_to climbers_welcome_path(climber)
    else
      flash[:no_user] = "Username or password is incorrect."
      redirect_to "/"
    end
  end

  def logout
    session.clear 
    redirect_to '/'
  end

  def new
    @climber = Climber.new
  end

  def create
    @climber = Climber.new(climber_params)
    if @climber.save
      session[:climber_id] = @climber.id
      cookies["this_page_climber"] = @climber.id
      redirect_to edit_climber_path(@climber)
    else
      render :new
    end
  end

  def profile
    @climber = Climber.find_by(id: session[:climber_id])
    
    communities = params["climber"]["communities"]
    communities.shift
    communities.each do |community|
      @climber.communities << Community.find(community.to_i)
    end
    if @climber.save
      redirect_to climber_path(@climber.id)
    else 
      render :new
    end
  end

  def edit
    if authorized_to_edit(cookies["this_page_climber"])
      render :edit
    else
      flash[:notice] = "You can only edit your own information."
      redirect_to climber_path(cookies["this_page_climber"].to_i)
    end
  end

  def update
    @climber.update(profile_params)
    if @climber.save
      join_communities(params["climber"]["communities"])
      redirect_to climber_path(@climber)
    else
      render :edit
    end
  end

  def destroy
    redirect_to climber_path(@climber)
  end

  def remove_route
    @route = Route.find(params["format"].to_i)
    @climber = Climber.find(session["climber_id"])
    if authorized_to_edit(cookies["this_page_climber"])
      @climber.routes.delete(@route.id)
      redirect_to climber_path(@climber)
    else
      flash[:notice] = "You can only edit your own information."
      redirect_to climber_path(cookies["this_page_climber"].to_i)
    end
  end

  def remove_community
    @community = Community.find(params["format"].to_i)
    @climber = Climber.find(session["climber_id"])
    if authorized_to_edit(cookies["this_page_climber"])
      @climber.communities.delete(@community.id)
      redirect_to climber_path(@climber)
    else
      flash[:notice] = "You can only edit your own information."
      redirect_to climber_path(cookies["this_page_climber"].to_i)
    end

  end

  private


  def find_climber
    @climber = Climber.find(params[:id])
  end

  def climber_params
    params.require(:climber).permit(:username, :password)
  end

  def profile_params
    params.require(:climber).permit(:name, :experience, :birthyear, :bio, :height, :weight, :origin, :preference, :profile_pic)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update]
  before_action :authorized
  
  def show
    @community = Community.find(@post["community_id"])
    cookies["this_posts_climber_id"] = @post.climber.id
    cookies["this_posts_community_id"] = @community.id
  end

  def new
    @post = Post.new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    params["post"]["community_id"] = cookies[:community_id]
    params["post"]["climber_id"] = session[:climber_id]
    @post = Post.new(post_params)
    if @post.save
      flash[:message] = "Post successfully added!"
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def edit
    if authorized_to_edit(cookies["this_posts_climber_id"])
      render :edit
    else
      flash["notice"] = "Can only edit your own posts."
      redirect_to post_path(@post)
    end
  end

  def update
    @post.update(post_params)
    if @post.save
      flash[:message] = "Post successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:format].to_i)
    @community = Community.find(@post["community_id"])
    if authorized_to_edit(cookies["this_posts_climber_id"])
      @post.destroy
      flash[:danger] = "Post deleted"
      redirect_to community_path(@community.id)
    else
      flash["notice"] = "Can only delete your own posts."
      redirect_to post_path(@post.id)
    end
  end

  private

  def post_params
    params.require(:post).permit(:climber_id, :community_id, :subject, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



  
end

app/helpers/climbers_helper.rb
module ClimbersHelper

  # def current_user
  #   Climber.find(id: session[:climber_id])
  # end

  def logged_in?
    !current_user.nil?
  end

  def check_session
    puts session[:climber_id]
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper





end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/climbers/_climber_form.html.erb
<% if @climber.errors %>
  <% @climber.errors.full_messages.each do |error|%>
    <%= error %>
  <% end %>
<% end %>

<center>
<div class="climber-create-bg"> 
    <div class="climber-create-box">
          <h1 style="font-size:40px">"It is not the mountain that we conquer, but ourselves."</h1>
          <br><br>
          <div class="ui form">
          <label>
          <%=form_for @climber do |f| %> 
            <%=f.label :name, "Full name: " %><br>
            <%=f.text_field :name%>
            <br><br>
            <%=f.label :experience, "Experience: " %><br>
            <%=f.text_field :experience%> 
            <br><br>
            <%=f.label :birthyear, "Birthyear: "%><br>
            <%=f.number_field :birthyear%> 
            <br><br>
            <%=f.label :height, "Height: "%><br>
            <%=f.text_field :height%> 
            <br><br>
            <%=f.label :weight, "Weight: "%><br>
            <%=f.number_field :weight%> 
            <br><br>
            <%=f.label :origin, "Location: " %><br>
            <%=f.text_field :origin, required: true %> 
            <br><br>
            <%=f.label :preference, "Preference: "%><br>
            <%=f.text_field :preference%>
            <br><br>
            </label>

  <%=f.label :communities, "Community: " %><br><br>
  <%=f.collection_check_boxes(:communities, Community.all, :id,:name) do |b|%>
    <div class="climber-edit-checkbox">
    <%= b.check_box(class: "check_box") + b.text %>
    </div>
  <% end %>
  <br><br>
  <%# f.collection_check_boxes(:communities, Community.all, :id, :name) do |b| %>
  <%# b.label(class: "check_box") { b.check_box(checked: true, class: "add_margin") + b.text } %>
  <%# end %>




  <%=f.label :bio, "Biography: " %><br>
  <%=f.text_area :bio%> 
  <br><br>
  <%=f.label :profile_pic, "Profile Picture(URL): " %> <br>
  <%=f.text_field :profile_pic%>
  <br><br>
  <button class="ui blue button">
  <%f.submit %>Submit!
  </button>
  <br><br>
      </div>
    </div>
  </div>
<%end%>
</center>

app/views/climbers/_climber_weather_display.html.erb
<div class="ui inverted segment weather-display">
<div class="card text-white bg-dark mb-3">
  <div class="card-header"><img src="<%= @api["weather_icons"][0] %>" alt="A picture of the location <%= current_user.origin %>"></div>
  <h5 id="weather-title">Current Weather</h5>
  <p><%= @api["weather_descriptions"][0] %></p>
  <p><%= @api["temperature"] %>˚F</p>
  <p>The humidity is <%= @api["humidity"] %>%.</p>
</div>
</div>

app/views/climbers/edit.html.erb
<%= render partial: "climber_form", locals: {button_text: "Edit Profile"} %> 

app/views/climbers/index.html.erb
<!DOCTYPE html>
<html>
<body>

<%= render partial: "partials/navbar" %> 

<center>
<div class="climbers-body">
<h1 style="font-size:45px">The Climbers: </h1>
<ul> 
<% @climbers.all.each do |climber| %> 
  <li><%= link_to climber.name, climber_path(climber)%></li>
  <%end%>
</ul>
<br>
<br>
</div>
</body>
</html>

app/views/climbers/new.html.erb
<% if @climber.errors %>
  <ul>
    <% @climber.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<div class="climber-new-bg">
  <div class="climber-new-box">
  <center><h1 style=font-size:40px">Join the Adventure!</h1></center>
  <br><br><br>
    <div class="ui form"> 
    <center>
      <%= form_for (@climber) do |f| %> 
        <%= f.label :username%><br>
        <%= f.text_field :username, required: true%><br><br>
        <%= f.label :password%><br>
        <%= f.password_field :password, required: true%>
        <br><br>
        <button class="ui blue button">
        <%f.submit %>Submit!
        </button>
      <%end%>
      <br><br>
      <button lass="arrow circle left icon">
        <i class="arrow circle left icon"></i>
        <%= link_to "Go Back", '/'%> 
      </button>
      </div>
    </div>
  </div>
</center>

app/views/climbers/profile.html.erb
<%= render partial: "climber_form", locals: {button_text: "Create a Profile!"}%>

app/views/climbers/show.html.erb
<!DOCTYPE html>
<html>
<body>

<%= render partial: "partials/navbar" %> 
<div class="flash-info-for-all-pages"><%= flash[:notice] %></div>

<div class="climbers-body">
<center><h1>What's the scoop on <%=@climber.name%>?</h1>
    <br><br>
    <%= image_tag("#{@climber.profile_pic}", class: "climber-show-image", height: "30%", width: "45%")%></center>
    <br><br>

<center>
  <button class="ui standard button">
  <i class="edit icon"></i>
  <%= link_to "Edit Profile", edit_climber_path(@climber)%>
</button>
<br><br>

<div class="ui divider"></div>
  <div class="climber-show-list">
    <div class="ui two column vertically padded grid">
      <div class="column">
        <p><center>
        <h2 class="climber-show-info-header">Experience:</h2>
        <h5 class="climber-show-info-body"><%=@climber.experience%></h5>
        <h2 class="climber-show-info-header">Birthyear:</h2>
        <h5 class="climber-show-info-body"><%=@climber.birthyear%></h5>
        <h2 class="climber-show-info-header">Height:</h2>
        <h5 class="climber-show-info-body"><%=@climber.height%> </h5>
        <h2 class="climber-show-info-header">Weight:</h2>
        <h5 class="climber-show-info-body"><%=@climber.weight%></h5>
        <h2 class="climber-show-info-header">Location:</h2>
        <h5 class="climber-show-info-body"><%=@climber.origin%></h5>
        <h2 class="climber-show-info-header">Climbing Preference:</h2>
        <h5 class="climber-show-info-body"><%=@climber.preference%></h5>
        </center></p>
      </div>
      <div class="column">

    <h2 class="climber-show-info-header">In The Works: </h2> 
    <%@routes.each do |route|%> 
      <h5 class="climber-show-project-link">
      <%= link_to route.name, route_path(route) %> </h5>
        <div class="ui small basic icon buttons">
          <button class="ui button">
            <i class="trash alternate icon"></i>
                <%= link_to "Delete", climber_remove_route_path(route), { class: "climber-show-remove-link" } %>
          </button>
        </div>
      <%end%>

    <br><br>

      <h2 class="climber-show-info-header">Communities <%=@climber.name%> is in:</h2>
      <%@communities.each do |community|%>
        <h5><%= link_to community.name, community_path(community)%></h5>
          <div class="ui small basic icon buttons">
            <button class="ui button">
            <i class="trash alternate icon"></i>
            <%= link_to "Delete", climber_remove_community_path(community.id), { class: "climber-show-remove-link" } %>
            </button>
          </div>
      <%end%>
      
        </div>
      </div>
    <h2 class="climber-show-info-header">Biography:</h2>
    <h5><p><%=@climber.bio%></p></h5>
    </div>
  </div>
</div>

</body>
</html>

app/views/climbers/welcome.html.erb
<!DOCTYPE html>
<html>
<body>

<%= render partial: "partials/navbar" %> 

<div class="welcome-body">
<div class= "welcome-body-text">
<center>
<img src="https://i.ytimg.com/vi/kQxF3H6TYsc/maxresdefault.jpg"  width="50%" height="60%">
<br>
<h1>Welcome back <%=current_user.name%>!</h1>
<br><br>
<h3 class="climber-welcome-header">What's the weather like in <%=current_user.origin%>?</h3>
<br>
<%= render partial: "climber_weather_display" %>
<br><br>
<h1 class="climber-welcome-header">Your projects: </h1>
<% @routes.each do |route|%> 
  <li><%= link_to route.name, route_path(route)%> </li>
<%end%>

<br><br>
</center>
<br><br>
<center>

<h1 class="climber-welcome-header">Check out who's crushing it! </h1>
<br><br>
<% get_current_events.each do |k, v| %> 
  <%= k %> is climbing: 
  <br><br>
  <%v.each do |single_route| %> 
  <%= single_route%>
  <br>
  <%end%>
  <br><br>
<%end%>

</div>
</div>
</center>
</body>
</html>