config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#home", as: "home_path"
  
  get 'climbers/new'
  get 'climber/profile', to: 'climbers#profile'
  # get 'climbers/login', to: 'climbers#login'
  post 'climbers/login', to: 'climbers#process_login'
  get 'climbers/logout', to: 'climbers#logout'
  get 'climbers/welcome', to: 'climbers#welcome'
  #trim this file down to just the routes you need upon refactoring
  resources :communities
  resources :locations
  resources :projects
  resources :routes
  resources :climbers
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'post/delete', to: 'posts#destroy'

  get 'climber/remove_community', to: 'climbers#remove_community'
  get 'climber/remove_route', to: 'climbers#remove_route'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/climber.rb
class Climber < ApplicationRecord
  has_secure_password

  has_many :projects
  has_many :routes, through: :projects
  has_many :posts
  has_many :communities, through: :posts
  has_many :comments
  
  validates :username, uniqueness: {case_sensitive: false, message: " must be unique."}
  

  def delete_route(route_obj)
    @climber.routes.each do |route|
      if route == route_obj
        route.delete
      end
    end
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :climber
  belongs_to :post

  validates :message, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :posts
  has_many :climbers, through: :posts
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :routes



  def all_routes
    self.routes.map
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :climber
  belongs_to :community
  has_many :comments

  # validates :subject, presence: true
  # validates :content, presence: true
  
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :climber
  belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :location
  has_many :projects
  has_many :climbers, through: :projects

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :difficulty, :location, presence: true
  validates :style, presence: true

  def add_like
    self.likes += 1
    self.save
  end

end

app/models/user.rb
class User < ApplicationRecord


  

  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update]
  before_action :authorized
  
  def show
    @community = Community.find(@post["community_id"])
    cookies["this_posts_climber_id"] = @post.climber.id
    cookies["this_posts_community_id"] = @community.id
  end

  def new
    @post = Post.new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    params["post"]["community_id"] = cookies[:community_id]
    params["post"]["climber_id"] = session[:climber_id]
    @post = Post.new(post_params)
    if @post.save
      flash[:message] = "Post successfully added!"
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def edit
    if authorized_to_edit(cookies["this_posts_climber_id"])
      render :edit
    else
      flash["notice"] = "Can only edit your own posts."
      redirect_to post_path(@post)
    end
  end

  def update
    @post.update(post_params)
    if @post.save
      flash[:message] = "Post successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:format].to_i)
    @community = Community.find(@post["community_id"])
    if authorized_to_edit(cookies["this_posts_climber_id"])
      @post.destroy
      flash[:danger] = "Post deleted"
      redirect_to community_path(@community.id)
    else
      flash["notice"] = "Can only delete your own posts."
      redirect_to post_path(@post.id)
    end
  end

  private

  def post_params
    params.require(:post).permit(:climber_id, :community_id, :subject, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def login
    
  end



 

  private




end

app/helpers/application_helper.rb
module ApplicationHelper



  
end

app/helpers/climbers_helper.rb
module ClimbersHelper

  # def current_user
  #   Climber.find(id: session[:climber_id])
  # end

  def logged_in?
    !current_user.nil?
  end

  def check_session
    puts session[:climber_id]
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper





end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_post_form.html.erb
<%= render partial: "partials/navbar" %> 

<div class="post-create-bg">
  <div class="post-create-box">
    <div class="ui form">

        <label>
          <%=form_for @post do |f| %> 
            <%=f.label :subject, "Subject: " %>
            <%=f.text_field :subject, required: true%> 
            <br><br>
            <%=f.label :content, "Content: " %>
            <%=f.text_area :content, required:  true%> 
            <br><br>
            <button class="ui standard button">
            <%f.submit %>Submit!
            </button>
            <%end%>
        </label>

    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render partial: "post_form" %> 

app/views/posts/new.html.erb
<%= render partial: "post_form" %> 

app/views/posts/show.html.erb
<div class="post-show">
<%= render partial: "partials/navbar" %> 
<div class="flash-info-for-all-pages"><%= flash[:notice] %></div>

<center>
<div class="post-title-box">
<h1> <%=@post.subject%> </h1>
</div>
<div class="post-content-box">
<h5> <%=@post.content%> </h5> 
</div>
<br><br>
<div class="post-text-box">
<h3> Comments: </h3>
<br>
  <div class="comment-alignment">
    <% @post.comments.each do |comment| %> 
    <p>
    <%comment_time = comment[:created_at].strftime('%m/%d/%y %I:%M %p')%> 
      <%= comment_time %> : <%= comment.climber.username %> : <%= comment.message %>
    </p>
<%end%> 
</div>
<br><br>
<button class="ui white button">
<%= link_to "Add Comment", new_comment_path(post_id: @post.id) %> </button> 
</div>
<br><br>
    <button class="ui black button">
      <i class="trash alternate icon"></i>
      <%= link_to "Delete", post_delete_path(@post), { class: "post-show-remove-link" } %>
    </button>
<button class="ui black button">
<%= link_to "Edit Post", edit_post_path(@post)%>
</button>
<button class="ui black button">
<%= link_to "Back", community_path(@post.community.id)%> 
</button>

</center>

</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/login.html.erb
<h1>Users#login</h1>
<p>Find me in app/views/users/login.html.erb</p>

app/views/users/logout.html.erb
<h1>Users#logout</h1>
<p>Find me in app/views/users/logout.html.erb</p>

app/views/users/show.html.erb
<h1> Welcome You dirtbag!</h1>
<p><%= "Just kidding your name is #{current_username}." %></p>
<% get_current_events().each do |climber| %>
  <%= climber %>
<% end %>