config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#home", as: "home_path"
  
  get 'climbers/new'
  get 'climber/profile', to: 'climbers#profile'
  # get 'climbers/login', to: 'climbers#login'
  post 'climbers/login', to: 'climbers#process_login'
  get 'climbers/logout', to: 'climbers#logout'
  get 'climbers/welcome', to: 'climbers#welcome'
  #trim this file down to just the routes you need upon refactoring
  resources :communities
  resources :locations
  resources :projects
  resources :routes
  resources :climbers
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'post/delete', to: 'posts#destroy'

  get 'climber/remove_community', to: 'climbers#remove_community'
  get 'climber/remove_route', to: 'climbers#remove_route'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/climber.rb
class Climber < ApplicationRecord
  has_secure_password

  has_many :projects
  has_many :routes, through: :projects
  has_many :posts
  has_many :communities, through: :posts
  has_many :comments
  
  validates :username, uniqueness: {case_sensitive: false, message: " must be unique."}
  

  def delete_route(route_obj)
    @climber.routes.each do |route|
      if route == route_obj
        route.delete
      end
    end
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :climber
  belongs_to :post

  validates :message, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :posts
  has_many :climbers, through: :posts
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :routes



  def all_routes
    self.routes.map
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :climber
  belongs_to :community
  has_many :comments

  # validates :subject, presence: true
  # validates :content, presence: true
  
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :climber
  belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :location
  has_many :projects
  has_many :climbers, through: :projects

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :difficulty, :location, presence: true
  validates :style, presence: true

  def add_like
    self.likes += 1
    self.save
  end

end

app/models/user.rb
class User < ApplicationRecord


  

  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update]
  before_action :authorized
  
  def show
    @community = Community.find(@post["community_id"])
    cookies["this_posts_climber_id"] = @post.climber.id
    cookies["this_posts_community_id"] = @community.id
  end

  def new
    @post = Post.new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    params["post"]["community_id"] = cookies[:community_id]
    params["post"]["climber_id"] = session[:climber_id]
    @post = Post.new(post_params)
    if @post.save
      flash[:message] = "Post successfully added!"
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def edit
    if authorized_to_edit(cookies["this_posts_climber_id"])
      render :edit
    else
      flash["notice"] = "Can only edit your own posts."
      redirect_to post_path(@post)
    end
  end

  def update
    @post.update(post_params)
    if @post.save
      flash[:message] = "Post successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:format].to_i)
    @community = Community.find(@post["community_id"])
    if authorized_to_edit(cookies["this_posts_climber_id"])
      @post.destroy
      flash[:danger] = "Post deleted"
      redirect_to community_path(@community.id)
    else
      flash["notice"] = "Can only delete your own posts."
      redirect_to post_path(@post.id)
    end
  end

  private

  def post_params
    params.require(:post).permit(:climber_id, :community_id, :subject, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :find_route, only: [:show, :edit, :update, :delete]
  # skip_before_action :verify_authenticity_token
  before_action :authorized
  def index
    @routes = Route.all 
  end

  def show
    @climbers = @route.climbers.uniq
  end

  def new
    @route = Route.new
  end

  def create
    params[:route][:location_id] = params[:route][:id]
    @route = Route.new(route_params)
    if @route.save
      redirect_to route_path(@route.id)
    else
      render :edit
    end
  end

  def edit
  end

  def update
    if params[:add_like]
      @route.add_like
      redirect_to route_path(@route)
    elsif params[:add_route]
      Climber.find(session[:climber_id]).routes.push(@route)
      redirect_to route_path(@route)
    else
      @route.update(route_params)
      if @route.save
        redirect_to route_path(@route)
      else
        render :edit
      end
    end
  end

  def destroy
    redirect_to routes_path
  end


  private

  def find_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, :difficulty, :style, :location_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



  
end

app/helpers/climbers_helper.rb
module ClimbersHelper

  # def current_user
  #   Climber.find(id: session[:climber_id])
  # end

  def logged_in?
    !current_user.nil?
  end

  def check_session
    puts session[:climber_id]
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper





end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/routes/_route_input_form.html.erb
<%= render partial: "partials/navbar" %> 

<% if @route.errors %>
  <% @route.errors.full_messages.each do |error|%>
    <p class="route-create-error-list"><%= error %></p>
  <% end %>
<% end %>

<div class="route-form-bg">
  <div class="route-form-textbox">
        <div class="ui form">
          <%= form_for @route do |f| %>
            <h3><%= f.label "Name:" %><br></h3>
            <%= f.text_field :name %><br><br>
            <h3><%= f.label "Difficulty:" %><br></h3>
            <%= f.text_field :difficulty %><br><br>
            <h3><%= f.label "Style:" %><br></h3>
            <%= f.text_area :style %><br><br>
            <h3><%= f.label "Location:" %><br></h3>
            <%= f.collection_select(:id, Location.all, :id, :name) %><br><br>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/routes/edit.html.erb
<%= render partial: "route_input_form" %>
<h1>Edit <%= @route.name %></h1>

app/views/routes/index.html.erb
<!DOCTYPE html>
<html>
<body>

<%= render "partials/navbar" %> 

<div class="route-index-body">

<center>
<h1 style="font-size:45px">Routes</h1>
<br>
<div class="routes-index-list">
  <% @routes.each do |route| %>
    <h3><%= link_to route.name, route_path(route), {class: "routes-index-to-route-show-link"} %></h3>
    <p>Location: <%= link_to route.location.name, location_path(route.location), {class: "routes-index-to-location-show-link"} %><br><br></p>
  <br>
  <% end %>
  <button class="ui standard button">
  <%= link_to "Create New Route", new_route_path, method: "get" %>
  </button>
</div>
</center>
</div>
</html>
</body>

app/views/routes/new.html.erb
<%= render partial: "route_input_form" %>

app/views/routes/show.html.erb
<!DOCTYPE html>
<html>

<body>

  <%= render "partials/navbar" %>

  <div class="route-body">
    <center>
      <h1><%= @route.name %></h1>
      <br><br>
      <p><img src="<%= @route.picture %>" class="route-show-image"
          alt="A picture of the climbing face with an overlay of the route <%= @route.name %>" height="40%" width="40%">
      </p>


      <div class="ui labeled button" tabindex="0">

        <%= form_for @route do |f| %>
        
          <%= button_to "Like!", route_path(@route), params: { add_like: true}, class: "ui red button"%>
          <a class="ui basic red left pointing label">
            <%= @route.likes %>
          </a>
        <% end %>
      </div>

      <br><br>
      <div class="route-show-list">

        <h3 class="route-show-info-header">Difficulty:</h3>
        <div class="route-show-info-body"><%= @route.difficulty %></div>
        <h3 class="route-show-info-header">Style:</h3>
        <div class="route-show-info-body"><%= @route.style %></div>
        <h3>Climbers projecting this route:</h3>
        <% @climbers.each do |climber| %>
        <p><%= link_to climber.name, climber_path(climber), {class: "route-to-climber-link"} %></p>
        <% end %>
        <%= form_for @route do |f| %>
          <%= button_to "Add Project", route_path(@route), params: { add_route: true } %>
        <% end %>

        <br><br>
        <button class="edit outline icon">
          <i class="edit icon"></i>
          <%= link_to "Edit", edit_route_path(@route), method: "get" %>
        </button>
      </div>
    </center>
  </div>
</body </html>