config/routes.rb
Rails.application.routes.draw do
  get "/", to: "home#home", as: "home_path"
  
  get 'climbers/new'
  get 'climber/profile', to: 'climbers#profile'
  # get 'climbers/login', to: 'climbers#login'
  post 'climbers/login', to: 'climbers#process_login'
  get 'climbers/logout', to: 'climbers#logout'
  get 'climbers/welcome', to: 'climbers#welcome'
  #trim this file down to just the routes you need upon refactoring
  resources :communities
  resources :locations
  resources :projects
  resources :routes
  resources :climbers
  resources :comments, only: [:new, :create, :edit, :update, :destroy]
  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]
  get 'post/delete', to: 'posts#destroy'

  get 'climber/remove_community', to: 'climbers#remove_community'
  get 'climber/remove_route', to: 'climbers#remove_route'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/climber.rb
class Climber < ApplicationRecord
  has_secure_password

  has_many :projects
  has_many :routes, through: :projects
  has_many :posts
  has_many :communities, through: :posts
  has_many :comments
  
  validates :username, uniqueness: {case_sensitive: false, message: " must be unique."}
  

  def delete_route(route_obj)
    @climber.routes.each do |route|
      if route == route_obj
        route.delete
      end
    end
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :climber
  belongs_to :post

  validates :message, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :posts
  has_many :climbers, through: :posts
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :routes



  def all_routes
    self.routes.map
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :climber
  belongs_to :community
  has_many :comments

  # validates :subject, presence: true
  # validates :content, presence: true
  
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :climber
  belongs_to :route
end

app/models/route.rb
class Route < ApplicationRecord
  belongs_to :location
  has_many :projects
  has_many :climbers, through: :projects

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :difficulty, :location, presence: true
  validates :style, presence: true

  def add_like
    self.likes += 1
    self.save
  end

end

app/models/user.rb
class User < ApplicationRecord


  

  


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :find_location, only: [:show, :edit, :update, :delete]
  before_action :authorized
  
  def index
    @locations = Location.all
  end

  def show
    #before_action above pasees the @location

    @api = get_the_weather()["current"]
    
    # @parsed = JSON.parse(@api)
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create(location_params)
    if @location.save
      redirect_to location_path(@location.id)
    else
      render :new
    end
  end

  def edit
    #before_action above pasees the @location
  end

  def update
    @location.update(location_params)
    if @location.save
      redirect_to location_path(@location)
    else
      render :edit
    end
  end

  def destroy
    redirect_to locations_path
  end

  private

  def find_location
    @location = Location.find(params[:id])
  end
  
  def location_params
    params.require(:location).permit(:name, :rock_type, :approach, :popularity, :picture)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update]
  before_action :authorized
  
  def show
    @community = Community.find(@post["community_id"])
    cookies["this_posts_climber_id"] = @post.climber.id
    cookies["this_posts_community_id"] = @community.id
  end

  def new
    @post = Post.new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    params["post"]["community_id"] = cookies[:community_id]
    params["post"]["climber_id"] = session[:climber_id]
    @post = Post.new(post_params)
    if @post.save
      flash[:message] = "Post successfully added!"
      redirect_to post_path(@post.id)
    else
      render :new
    end
  end

  def edit
    if authorized_to_edit(cookies["this_posts_climber_id"])
      render :edit
    else
      flash["notice"] = "Can only edit your own posts."
      redirect_to post_path(@post)
    end
  end

  def update
    @post.update(post_params)
    if @post.save
      flash[:message] = "Post successfully updated!"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:format].to_i)
    @community = Community.find(@post["community_id"])
    if authorized_to_edit(cookies["this_posts_climber_id"])
      @post.destroy
      flash[:danger] = "Post deleted"
      redirect_to community_path(@community.id)
    else
      flash["notice"] = "Can only delete your own posts."
      redirect_to post_path(@post.id)
    end
  end

  private

  def post_params
    params.require(:post).permit(:climber_id, :community_id, :subject, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



  
end

app/helpers/climbers_helper.rb
module ClimbersHelper

  # def current_user
  #   Climber.find(id: session[:climber_id])
  # end

  def logged_in?
    !current_user.nil?
  end

  def check_session
    puts session[:climber_id]
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper





end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/locations/_location_input_form.html.erb
<%= render partial: "partials/navbar" %> 

<% if @location.errors %>
  <% @location.errors.full_messages.each do |error|%>
    <%= error %>
  <% end %>
<% end %>

<div class="location-create-form-bg">
  <div class="location-form-box">

    <center>
    <div class="ui form">
    <%= form_for @location do |f| %>
      <h3><%= f.label "Name:" %><br></h3>
      <%= f.text_field :name %><br><br>
      <h3><%= f.label "Rock Type:" %><br></h3>
      <%= f.text_field :rock_type %><br><br>
      <h3><%= f.label "Approach:" %><br></h3>
      <%= f.text_area :approach %><br><br>
      <h3><%= f.label "Popularity:" %><br></h3>
      <%= f.text_field :popularity %><br><br>
      <h3><%= f.label "Picture:" %><br></h3>
      <%= f.text_area :picture %><br><br>
      <br><br>
      <button class="ui blue button">
      <%f.submit %>Submit!
      </button>
    <% end %>
    </div>
  </div>
</div>
</center>

app/views/locations/_location_weather_display.html.erb
<div class="ui inverted segment weather-display">
  <div class="card text-white bg-dark mb-3">
    <div class="card-header"><img src="<%= @api["weather_icons"][0] %>" alt="A picture of the location <%= @location.name %>"></div>
    <h5 id="weather-title">Current Weather</h5>
    <p><%= @api["weather_descriptions"][0] %></p>
    <p><%= @api["temperature"] %>˚F</p>
    <p>The humidity is <%= @api["humidity"] %>%.</p>
  </div>
</div>

app/views/locations/edit.html.erb
<%= render partial: "location_input_form" %>

app/views/locations/index.html.erb
<!DOCTYPE html>
<html>
<body>

<%= render partial: "partials/navbar" %> 

<div class="location-index-body">
  <center>
  <h1 style="font-size:45px">Locations</h1>
  <br>
  <div class="location-index-list">
  
    <% @locations.each do |location| %>
      <a href="/locations/<%= location.id %>" class="location-index-link">
      <img src="<%= location.picture %>" class="location-index-img" alt="A picture of the location <%= location.name %>" height="50%" width="50%">
      <br>
      <%= location.name %>
      </a>
      <br>
      <br>
    <% end %>
  

    <br>
    <br>
    <button class="ui white button">
    <%= link_to "Add a New Location", new_location_path, method: "get" %>
    </button>
    </div>
</div>

</body>
</html>

app/views/locations/new.html.erb
<%= render partial: "location_input_form" %>

app/views/locations/show.html.erb
<!DOCTYPE html>
<html>
<body>

<%= render partial: "partials/navbar" %> 

<div class="location-body">
<br><br>
<center>
<p><img src="<%= @location.picture %>" alt="A picture of the location <%= @location.name %>" height="40%" width="40%"></p>

<h1><%= @location.name %></h1>


<%= render partial: "location_weather_display" %>

<div class="location-show-list">
  <h3 class="location-show-info-header">Rock Type:</h3><div class="location-show-info-body"> <br><%= @location.rock_type %></div>
  <h3 class="location-show-info-header">Approach:</h3><div class="location-show-info-body"> <br><%= @location.approach %></div>
  <h3 class="location-show-info-header">Popularity:</h3><div class="location-show-info-body"> <br><%= @location.popularity %></div>

  <br>
  <center>
  <button class="edit outline icon">
    <i class="edit icon"></i>
    <%= link_to "Edit", edit_location_path(@location), method: "get"%>
  </button>

  <h2 id="location-show-routes-header">Routes:</h2>

  <% @location.routes.each do |route| %>
    <p><%= link_to route.name, route_path(route), {class: "location-route-links"}%></p>
  <% end %>
</div>

</center>

</div>
</body>
</html>